export const majorArcana = [
  { name: 'The Fool', keywords: 'Beginnings, innocence, spontaneity, a free spirit.' },
  { name: 'The Magician', keywords: 'Manifestation, resourcefulness, power, inspired action.' },
  { name: 'The High Priestess', keywords: 'Intuition, sacred knowledge, divine feminine, the subconscious mind.' },
  { name: 'The Empress', keywords: 'Femininity, beauty, nature, nurturing, abundance.' },
  { name: 'The Emperor', keywords: 'Authority, establishment, structure, a father figure.' },
  { name: 'The Hierophant', keywords: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.' },
  { name: 'The Lovers', keywords: 'Love, harmony, relationships, values alignment, choices.' },
  { name: 'The Chariot', keywords: 'Control, willpower, success, action, determination.' },
  { name: 'Strength', keywords: 'Strength, courage, patience, control, compassion.' },
  { name: 'The Hermit', keywords: 'Soul-searching, introspection, being alone, inner guidance.' },
  { name: 'Wheel of Fortune', keywords: 'Good luck, karma, life cycles, destiny, a turning point.' },
  { name: 'Justice', keywords: 'Justice, fairness, truth, cause and effect, law.' },
  { name: 'The Hanged Man', keywords: 'Pause, surrender, letting go, new perspectives.' },
  { name: 'Death', keywords: 'Endings, change, transformation, transition.' },
  { name: 'Temperance', keywords: 'Balance, moderation, patience, finding meaning.' },
  { name: 'The Devil', keywords: 'Shadow self, attachment, addiction, restriction, sexuality.' },
  { name: 'The Tower', keywords: 'Sudden change, upheaval, chaos, revelation, awakening.' },
  { name: 'The Star', keywords: 'Hope, faith, purpose, renewal, spirituality.' },
  { name: 'The Moon', keywords: 'Illusion, fear, anxiety, subconscious, intuition.' },
  { name: 'The Sun', keywords: 'Positivity, fun, warmth, success, vitality.' },
  { name: 'Judgement', keywords: 'Judgement, rebirth, inner calling, absolution.' },
  { name: 'The World', keywords: 'Completion, integration, accomplishment, travel.' }
];
